### ISSUE TITLE
Assigning reads to genes stuck with 3 genes left

### ISSUE THREAD

**Issue by ljwharbers** [OliverVoogd/FLAMES#41]
Hi,

Thanks for the nice tool!

I've been looking into using FLAMES for my gene/transcript quantification. I already have a customized pipeline for the demultiplexing/umi identification so I was looking to plug in FLAMES starting from the aligned and deduplicated bamfile. I've been making sure that the bamfile is formatted in the way it's required by FLAMES.

After generating the config file, everything seems to work fine, it goes straight into the read assignment and progresses nicely. However, when it gets to the last few genes it just halts and seems stuck (but there is still CPU usage from the FLAMES processes), see screenshot below.

<img width="1967" alt="image" src="https://github.com/user-attachments/assets/38ce8fc2-a1fd-4d8d-9486-291e9e672bba">

Have you seen this before and if yes, would you have a potential fix for this?

Many thanks,
Luuk

**Comment by youyupei** [comment]
Hi @ljwharbers , would you be able to share what output files have been generated?  At the end of gene quantification, FLAMES will try to summarize the UMI information and generate a deduplicated fastq file. The gene quantification is done if you to see the `*dedup.fastq` in your output dir. Otherwise,  would you be to check whether we are running out of memory?
