### ISSUE TITLE
question on UMI deduplication step 

### ISSUE THREAD

**Issue by sparthib** [OliverVoogd/FLAMES#46]
Hi there,

 In my output I see, `matched_reads_dedup.fastq` and `align2genome.bam` .
My question is, does UMI based deduplication occur at the `fastq` level, and is this `dedup.fastq` file then used for alignment? I just want to make sure that my BAM file doesn't have duplicate UMIs. 

Thanks,
Sowmya

**Comment by ChangqingW** [comment]
Our current UMI dedup is rather simplistic, it will just keep the longest read with the same UMI, rather than doing any consensus calling. 
The deduped one is used when realigning to the transcriptome (but not the initial `align2genome.bam`), you can double check this with `samtools view -H align2genome.bam` and the last few lines should tell you which command was used to produce the BAM file.

**Comment by sparthib** [comment]
Thanks, so if I understand correctly, the genome alignment still contains the duplicate reads but the transcriptome alignment doesn't?

**Comment by ChangqingW** [comment]
Yes, that's correct
